[features]
seeds = true
[programs.devnet]
solrpay = "G2FrpvYmW4z8uTts7JC38ucDQ9UqEnn2jEv3XwP7tngB"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/home/vsiva360/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
initialize = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/initialize.ts"
changepfp = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/changepfp.ts"
changename = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/changename.ts"

[test]
startup_wait = 10000
