[features]
seeds = true

[programs.devnet]
solrpay = "J2tPvtCtZ81u9QFZMi2ATVWnKVWjRU4P7TbJ1Q4wudMK"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/home/vsiva360/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
initialize = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/initialize.ts"
changepfp = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/changepfp.ts"
changename = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/changename.ts"
pay = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/pay.ts"
friends = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/friends.ts"
paytoken = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/paytoken.ts"