[features]
seeds = false

[programs.localnet]
solrpay = "5SChqz4YDGnrpto3jHTuzPYyvbcMcVwFDJ3EGzi3aX3L"

[programs.devnet]
solrpay = "5SChqz4YDGnrpto3jHTuzPYyvbcMcVwFDJ3EGzi3aX3L"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/Users/kevinz/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
initialize = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/initialize.ts"
changepfp = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/changepfp.ts"
changename = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/changename.ts"
pay = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/pay.ts"
friends = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/friends.ts"